web1/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from accounts import views
from django.conf import settings
from django.conf.urls import static
#####
app_name = 'accounts'
urlpatterns= [
    path('login/',auth_view.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('about/',views.About.as_view(),name ='about'),
    path('buy/',views.LandList.as_view(),name = 'buy'),
    path('buy/<int:pk>/',views.LandDetail.as_view(),name='detail'),
    path('sell/',views.SellList.as_view(),name='sell'),
    path('sellpost/',views.LandPost.as_view(),name='sellpost'),
    path('sell/<int:pk>/',views.sellDetail.as_view(),name='selldetail'),
    path('requests/',views.SellRequest.as_view(),name='requests'),
    path('requests/<int:pk>/',views.sellDetail.as_view(),name='requestsdetail'),
    path('delete/<int:pk>/',views.PostDelete.as_view(),name='delete'),
    path('buydelete/<int:pk>/',views.BuyDelete.as_view(),name='buydelete'),
    path('addbuy/',views.BuyCreate.as_view(),name = 'addbuy')

]

web1/web1/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web1/accounts/models.py
from django.db import models
from django.contrib import auth
from django.urls import reverse
from django.conf import settings
# Create your models here.
class LandBuy(models.Model):
    name = models.CharField(max_length=256)
    location = models.CharField(max_length=256)
    image = models.ImageField(blank=True,null=True,upload_to='Buyimages/')
    discription = models.TextField()
    size = models.IntegerField(blank=True,null=True,default=0)
    def __str__(self):
        return self.name
        def get_absolute_url(self):
            return reverse('accounts:buy',kwargs={'username':self.user.username,'pk':self.pk})
class User(auth.models.User,auth.models.PermissionsMixin):
    def __str__(self):
        return self.username
###################


class LandSellModel(models.Model):
    post_by = models.ForeignKey(auth.models.User,on_delete=models.CASCADE)
    Property_name = models.CharField(max_length=256)
    location = models.CharField(max_length=256)
    image = models.ImageField(null=True,blank=True,upload_to='images',default='D:\atom projects\webnew\web1\media\images\IMG_20190625_192316.jpg')
    discription = models.TextField()
    size = models.IntegerField(blank=True,null=True,default=0)
    def __str__(self):
        return self.Property_name
    def get_absolute_url(self):
        return reverse('accounts:sell',kwargs={'username':self.user.username,'pk':self.pk})

web1/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
#########
class UserCreateForm(UserCreationForm):
    class Meta:
        fields =('first_name','last_name','username','email','password1','password2')
        model = get_user_model()

    #    def __init__(self,*args,**kwargs):
        #    super().__init__(*args,**kwargs)
#class LandSellForm(forms.ModelForm):
#    class Meta:
#        model = LandSell

web1/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView,CreateView,DeleteView,ListView,DetailView,UpdateView
from accounts import forms
from accounts.models import LandBuy,LandSellModel
from accounts import models
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin

# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'
class Home(TemplateView):
    template_name = 'accounts/index.html'

class About(TemplateView):
    template_name = 'accounts/about.html'
class LandList(ListView):
    model = models.LandBuy
    context_object_name = 'land_list'
class LandDetail(DetailView):
    model = models.LandBuy
    template_name = 'accounts/detail.html'
    context_object_name = 'land_detail'

class LandPost(LoginRequiredMixin,CreateView):
    fields = ('Property_name','location','image','discription','size')
    model = models.LandSellModel
    success_url =reverse_lazy('accounts:sell')
    def form_valid(self,form):
        form.instance.post_by=self.request.user
        return super(LandPost,self).form_valid(form)
class SellList(LoginRequiredMixin,ListView):
    context_object_name = 'user_sell_list'
    def get_queryset(self):
        return LandSellModel.objects.filter(post_by=self.request.user)
    template_name ='accounts/landsell_list.html'
class sellDetail(LoginRequiredMixin,DetailView):
    model=models.LandSellModel
    context_object_name='sell_detail'
    template_name='accounts/sell_detail.html'
class SellRequest(ListView):
    model=models.LandSellModel
    context_object_name='requests'
    template_name='accounts/requests.html'
class PostDelete(LoginRequiredMixin,DeleteView):
    model=models.LandSellModel
    success_url=reverse_lazy('accounts:requests')
    template_name='accounts/delete.html'
class BuyCreate(LoginRequiredMixin,CreateView):
        fields = ('name','location','image','discription','size')
        model = models.LandBuy
        success_url =reverse_lazy('accounts:buy')
        template_name='accounts/addbuy.html'
class BuyDelete(LoginRequiredMixin,DeleteView):
    model=models.LandBuy
    success_url=reverse_lazy('accounts:buy')
    template_name='accounts/buydelete.html'

web1/accounts/templates/accounts/about.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block body %}
<br><br><br>
<h1>
  <em>Harish Bathla</em>
</h1>
<img id="dad" src="{% static 'IMG-20170807-WA0032.jpg' %}" alt="">
<br>
<hr>
<h4><em> Born is the Baran district of Rajasthan,highly experienced and cheerfull guy and always ready to help.
Perfect for you to select the best deals in the market </em> </h4>
<hr><br>
<h3>
  <em>Phone:9414286958</em>

</h3>
<hr><br>
<h3>
  <em>Address:pratap chock baran</em>
</h3>
{% endblock %}

web1/accounts/templates/accounts/addbuy.html
{% extends 'accounts/base.html' %}
{% load bootstrap3 %}
{% block body %}
<br><br><hr>
{% if user.is_superuser %}
<form  method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  <h6>Note:Here size is meter-square</h6>
  <input type="submit" class="btn btn-success" value="Add Property">
</form>
{% else  %}
<h3>
  <em>Please log in to access this feature</em>
  <a class="btn btn-primary" href="{% url 'accounts:login' %}">Login here</a>
</h3>
{% endif %}
{% endblock %}

web1/accounts/templates/accounts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
<link rel="stylesheet" href="{% static 'css/master.css' %}">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">



      <a class="navbar-brand" href="#">Bathla</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'accounts:about' %}">About Us</a>
            {% if user.is_superuser %}
          <a class="nav-item nav-link " href="{% url 'admin:index' %}">Admin</a>
        {% endif %}
          </div>


<div class="navbar-nav navbar-right">

{% if not user.is_authenticated %}
  <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
  <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">SignUp</a>
  {% else %}
    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
{% endif %}
  <a class="nav-item nav-link" href="{% url 'accounts:buy' %}">Buy </a>

{% if user.is_superuser %}
<a class="nav-item nav-link " href="{% url 'accounts:requests' %}">Sell Request</a>
{% else %}
<a class="nav-item nav-link" href="{% url 'accounts:sell' %}">Sell </a>
{% endif %}
</div>
</div>


    </nav>
    <div class="container">


  {% block body %}

  {% endblock %}
    </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
 </body>
</html>

web1/accounts/templates/accounts/buydelete.html
{% extends 'accounts/base.html' %}
{% block body %}
<br><br>
<hr>
<h1>Do you to Delete {{landbuy.name}} ?</h1>
<form  method="post">
  {% csrf_token %}
  <hr>
  <input type="submit" class="btn btn-danger"value="Delete" style="border:white 40px solid;">
  <a  class="btn btn-info"href="{% url 'accounts:detail' pk=landbuy.pk%}">Cancel</a>
</form>
{%endblock%}

web1/accounts/templates/accounts/delete.html
{% extends 'accounts/base.html' %}
{% block body %}
<br><br><h1>Do you to Delete {{landsellmodel.Property_name}} ?</h1>
<form  method="post">
  {% csrf_token %}
  <hr>
  <input type="submit" class="btn btn-danger"value="Delete">
  <a  class="btn btn-info"href="{% url 'accounts:requestsdetail' pk=landsellmodel.pk%}">Cancel</a>
</form>
{%endblock%}

web1/accounts/templates/accounts/detail.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block body %}

<br><br><br>
<h1 id="head">
  <em>
    Welcome !
  </em>
  <hr>
</h1>
<h2>
  <em>Name: {{land_detail.name}}</em>
</h2>
<hr>
<img  id="detailImg"src="{{land_detail.image.url}}" alt="">
<hr>
<h3>
  <em>  Location:{{land_detail.location}}</em>

</h3>
<hr>
<h3>
  <em>Disciption:{{land_detail.discription}}</em>
</h3>
<hr>
<h3>
  <em>Size:{{land_detail.size}}</em>
</h3>
<hr>
<a class="btn btn-danger"href="{% url 'accounts:buydelete' pk=land_detail.pk %}">Delete</a>
{% endblock %}

web1/accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %}
{% block body %}

<!--####-->
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://images.pexels.com/photos/1590046/pexels-photo-1590046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://images.pexels.com/photos/466685/pexels-photo-466685.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% endblock %}

web1/accounts/templates/accounts/landbuy_list.html
{% extends 'accounts/base.html' %}
{% block body %}
<br><br>
<h1>
  <em>List</em>
</h1>
<ol>
{% for land in land_list %}
<li>
  <div class="card" style="width: 18rem;">
    {% if land.image %}
    <img src="{{land.image.url}}" class="card-img-top" alt="...">
    {% else %}
  <img src="....." class="card-img-top" alt="Image not available">
    {%endif  %}
    <div class="card-body">
      <h5 class="card-title">Property</h5>
      <p class="card-text">{{land.name}}</p>
      <a href="{{land.id}}" class="btn btn-primary">Visit</a>
    </div>
  </div>
</li>
<hr>

{% endfor %}
</ol>
{% if user.is_superuser %}
<a class="btn btn-success"href="{% url 'accounts:addbuy' %}">Add More</a>
{% endif %}
{% endblock %}

web1/accounts/templates/accounts/landsell_list.html
{% extends 'accounts/base.html' %}
{% block body  %}
<br><br><hr>
{% if user.is_authenticated %}
<ol>
{% for p in user_sell_list %}
<li>
  <div class="card" style="width: 18rem;">
    <img src="{{ p.image.url }}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Property</h5>
      <p class="card-text">{{p.Property_name}}</p>
      <a href="{{p.id}}" class="btn btn-primary">Visit</a>
    </div>
  </div>


</li>
{% endfor %}

</ol>
{% endif %}
<a class="btn btn-info"href="{% url 'accounts:sellpost' %}">Post property</a>
{% endblock %}

web1/accounts/templates/accounts/landsellmodel_form.html
{% extends 'accounts/base.html' %}
{% load bootstrap3 %}
{% block body %}
<br><br><hr>
{% if user.is_authenticated %}
<form  method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <h6>Note:Here size is meter-square</h6>
  <input type="submit" class="btn btn-success" value="Find Buyer">
</form>
{% else  %}
<h3>
  <em>Please log in to access this feature</em>
  <a class="btn btn-primary" href="{% url 'accounts:login' %}">Login here</a>
</h3>
{% endif %}
{% endblock %}

web1/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load bootstrap3 %}
{% block body %}
<div class="container">
  <h1>
    <em>Login Here !</em>
  </h1>
  <form  method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-success" value="Login">
  </form>
</div>


{% endblock %}

web1/accounts/templates/accounts/requests.html
{% extends 'accounts/base.html' %}
{% block body %}
<br><br>
<h1>
  <em>Request of Selling</em>
  <br><hr>
</h1>
<ol>
{% for req in requests %}
<li>
  <div class="card" style="width: 18rem;">
    <img src="{{req.image.url}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Property</h5>
      <p class="card-text">{{req.Property_name}}</p>
      <a href="{{req.id}}" class="btn btn-primary">Visit</a>
    </div>
  </div>
</li>
<hr>

{% endfor %}
</ol>
{% endblock %}

web1/accounts/templates/accounts/sell_detail.html
{% extends 'accounts/base.html' %}
{% block body %}
<br><br><br>
<h1 id="head">
  <em>
    Welcome !
  </em>
  <hr>
</h1>
<h2>
  <em>Property Name: {{sell_detail.Property_name}}</em>
</h2>
<hr>
<img  id="detailImg"src="{{sell_detail.image.url}}" alt="">
<hr>
<h3>
  <em>  Location:{{sell_detail.location}}</em>

</h3>
<hr>
<h3>
  <em>Disciption:{{sell_detail.discription}}</em>
</h3>
<hr>
<h3>
  <em>Size:{{sell_detail.size}}</em>
</h3>
<hr>
<h3>
  <em>Buyer:{{sell_detail.post_by.first_name}} {{sell_detail.post_by.last_name}}</em>
</h3>
<hr>
<a class="btn btn-danger"href="{% url 'accounts:delete' pk=sell_detail.pk%}">Delete</a>
{% endblock %}

web1/accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% load bootstrap3 %}
{% block body %}
<div class="container">
  <h1>
    <em>Sign Up! Here</em>
  </h1>
  <form  method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-success" value="SignUp">
  </form>
</div>


{% endblock %}